package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	// HTTP Request Metrics
	HTTPRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"method", "endpoint", "status"},
	)

	HTTPRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"method", "endpoint"},
	)

	// Memory Management Metrics
	MemoryActiveSessions = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "lazy_ai_coder_memory_active_sessions",
			Help: "Number of active memory sessions",
		},
	)

	MemoryTotalMessages = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "lazy_ai_coder_memory_total_messages",
			Help: "Total number of messages stored in memory",
		},
	)

	MemoryTotalTokens = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "lazy_ai_coder_memory_total_tokens",
			Help: "Total number of tokens tracked in memory",
		},
	)

	MemorySummarizationsTotal = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_memory_summarizations_total",
			Help: "Total number of memory summarizations performed",
		},
	)

	MemoryCleanups = promauto.NewCounter(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_memory_cleanups_total",
			Help: "Total number of expired session cleanups",
		},
	)

	MemorySessionDuration = promauto.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_memory_session_duration_seconds",
			Help:    "Duration of memory sessions in seconds",
			Buckets: []float64{60, 300, 900, 1800, 3600, 7200, 14400, 28800, 43200, 86400},
		},
	)

	// LLM API Metrics
	LLMRequestsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_llm_requests_total",
			Help: "Total number of LLM API requests",
		},
		[]string{"model", "provider", "status"},
	)

	LLMRequestDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_llm_request_duration_seconds",
			Help:    "LLM API request duration in seconds",
			Buckets: []float64{0.5, 1, 2, 5, 10, 20, 30, 60},
		},
		[]string{"model", "provider"},
	)

	LLMTokensPrompt = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_llm_tokens_prompt",
			Help:    "Number of prompt tokens used in LLM requests",
			Buckets: []float64{100, 500, 1000, 2000, 4000, 8000, 16000},
		},
		[]string{"model"},
	)

	LLMTokensCompletion = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_llm_tokens_completion",
			Help:    "Number of completion tokens generated by LLM",
			Buckets: []float64{100, 500, 1000, 2000, 4000, 8000, 16000},
		},
		[]string{"model"},
	)

	LLMErrorsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_llm_errors_total",
			Help: "Total number of LLM API errors",
		},
		[]string{"model", "error_type"},
	)

	// MCP Tool Metrics
	MCPToolCallsTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_mcp_tool_calls_total",
			Help: "Total number of MCP tool calls",
		},
		[]string{"tool_name", "status"},
	)

	MCPToolDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_mcp_tool_duration_seconds",
			Help:    "MCP tool execution duration in seconds",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"tool_name"},
	)

	// WebSocket Metrics
	WebSocketConnectionsActive = promauto.NewGauge(
		prometheus.GaugeOpts{
			Name: "lazy_ai_coder_websocket_connections_active",
			Help: "Number of active WebSocket connections",
		},
	)

	WebSocketMessagesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_websocket_messages_total",
			Help: "Total number of WebSocket messages",
		},
		[]string{"direction"}, // "inbound" or "outbound"
	)

	// Database Metrics
	DatabaseQueriesTotal = promauto.NewCounterVec(
		prometheus.CounterOpts{
			Name: "lazy_ai_coder_database_queries_total",
			Help: "Total number of database queries",
		},
		[]string{"operation", "table"},
	)

	DatabaseQueryDuration = promauto.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "lazy_ai_coder_database_query_duration_seconds",
			Help:    "Database query duration in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0},
		},
		[]string{"operation", "table"},
	)
)

// RecordHTTPRequest records an HTTP request metric
func RecordHTTPRequest(method, endpoint, status string, duration float64) {
	HTTPRequestsTotal.WithLabelValues(method, endpoint, status).Inc()
	HTTPRequestDuration.WithLabelValues(method, endpoint).Observe(duration)
}

// RecordLLMRequest records an LLM API request metric
func RecordLLMRequest(model, provider, status string, duration, promptTokens, completionTokens float64) {
	LLMRequestsTotal.WithLabelValues(model, provider, status).Inc()
	LLMRequestDuration.WithLabelValues(model, provider).Observe(duration)
	if promptTokens > 0 {
		LLMTokensPrompt.WithLabelValues(model).Observe(promptTokens)
	}
	if completionTokens > 0 {
		LLMTokensCompletion.WithLabelValues(model).Observe(completionTokens)
	}
}

// RecordLLMError records an LLM API error
func RecordLLMError(model, errorType string) {
	LLMErrorsTotal.WithLabelValues(model, errorType).Inc()
}

// RecordMCPToolCall records an MCP tool call
func RecordMCPToolCall(toolName, status string, duration float64) {
	MCPToolCallsTotal.WithLabelValues(toolName, status).Inc()
	MCPToolDuration.WithLabelValues(toolName).Observe(duration)
}

// UpdateMemoryMetrics updates all memory-related metrics
func UpdateMemoryMetrics(activeSessions, totalMessages int, totalTokens int64) {
	MemoryActiveSessions.Set(float64(activeSessions))
	MemoryTotalMessages.Set(float64(totalMessages))
	MemoryTotalTokens.Set(float64(totalTokens))
}

// RecordMemorySummarization records a memory summarization event
func RecordMemorySummarization() {
	MemorySummarizationsTotal.Inc()
}

// RecordMemoryCleanup records a memory cleanup event
func RecordMemoryCleanup() {
	MemoryCleanups.Inc()
}

// RecordMemorySessionDuration records how long a session lasted
func RecordMemorySessionDuration(seconds float64) {
	MemorySessionDuration.Observe(seconds)
}

// RecordWebSocketConnection records WebSocket connection changes
func RecordWebSocketConnection(isConnect bool) {
	if isConnect {
		WebSocketConnectionsActive.Inc()
	} else {
		WebSocketConnectionsActive.Dec()
	}
}

// RecordWebSocketMessage records a WebSocket message
func RecordWebSocketMessage(direction string) {
	WebSocketMessagesTotal.WithLabelValues(direction).Inc()
}

// RecordDatabaseQuery records a database query
func RecordDatabaseQuery(operation, table string, duration float64) {
	DatabaseQueriesTotal.WithLabelValues(operation, table).Inc()
	DatabaseQueryDuration.WithLabelValues(operation, table).Observe(duration)
}
